# Generated by Django 5.0.6 on 2024-11-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softdeleteuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
